const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;
const DAYS_PER_WEEK = 7;

const ONE_SECOND = MILLISECONDS_PER_SECOND;
const ONE_MINUTE = ONE_SECOND * SECONDS_PER_MINUTE;
const ONE_HOUR = ONE_MINUTE * MINUTES_PER_HOUR;
const ONE_DAY = ONE_HOUR * HOURS_PER_DAY;

export {
  MILLISECONDS_PER_SECOND,
  SECONDS_PER_MINUTE,
  MINUTES_PER_HOUR,
  HOURS_PER_DAY,
  DAYS_PER_WEEK,
  ONE_SECOND,
  ONE_MINUTE,
  ONE_HOUR,
  ONE_DAY
};
